### ISSUE TITLE
error in my mac

### ISSUE THREAD

**Issue by kingaza** [VLOGroup/denoising-variationalnetwork#1]
$ python train_denoising_vn.py 
Traceback (most recent call last):
  File "train_denoising_vn.py", line 5, in <module>
    import vn
  File "/Users/abu/02_Work/denoising-variationalnetwork/vn/__init__.py", line 2, in <module>
    from .paramdefinitions import *
  File "/Users/abu/02_Work/denoising-variationalnetwork/vn/paramdefinitions.py", line 5, in <module>
    from tensorflow.contrib import icg
  File "/Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 38, in <module>
    from tensorflow.contrib import icg
  File "/Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/contrib/icg/__init__.py", line 31, in <module>
    from tensorflow.contrib.icg.python.ops.icg_ops import conv2d_complex, conv2d_transpose_complex
  File "/Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/contrib/icg/python/ops/icg_ops.py", line 11, in <module>
    _icg_ops_so = loader.load_op_library(resource_loader.get_path_to_datafile("_icg_ops.so"))
  File "/Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/contrib/icg/python/ops/_icg_ops.so, 6): Symbol not found: __Z24Fftshift2dKernelLauncherINSt3__17complexIdEEEvPKN10tensorflow6TensorEPS4_
  Referenced from: /Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/contrib/icg/python/ops/_icg_ops.so
  Expected in: flat namespace
 in /Users/abu/anaconda3/envs/vn/lib/python3.6/site-packages/tensorflow/contrib/icg/python/ops/_icg_ops.so

**Comment by kingaza** [comment]
I installed tensorflow-icg of CPU version. 
Is some op valid only in GPU version?

**Comment by kingaza** [comment]
Is there any plan for CPU version? thanks a lot.

**Comment by khammernik** [comment]
We added a CPU version for the ffttools in our [icg-tensorflow](https://github.com/VLOGroup/tensorflow-icg) repo.

**Comment by kingaza** [comment]
Thank you very much~~
